name: Deployment Workflow

on:
  workflow_run:
    workflows: ['Integration Workflow']
    types:
      - completed
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SEVER_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e

            echo "Changing directory to /www/wwwroot/clients/euclient"
            if ! cd /www/wwwroot/clients/euclient; then
              echo "Failed to change directory as required"
              exit 1
            fi

            echo "Pulling latest code from origin/main"
            if ! git pull origin main; then
              echo "Failed to pull latest code"
              exit 1
            fi

            echo "Installing dependencies with Yarn"
            if ! yarn install; then
              echo "Couldn't install packages with Yarn"
              exit 1
            fi

            # echo "Building for production"
            # if ! yarn build; then
            #   echo "Couldn't build project"
            #   exit 1
            # fi

            # echo "Starting production server with PM2"
            # if ! yarn deploy; then
            #   echo "Couldn't start production with PM2"
            #   exit 1
            # fi

            echo "Deployment successful"
