
name: Integration Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Check for linting issues
      run: yarn lint

    - name: Build
      run: yarn build


  Deploy-Preview:
    name: Deploy Preview

    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Set up SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER_NAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e
            echo "Changing directory to /www/wwwroot/CLIENTS/euclient"
            if ! cd /www/wwwroot/CLIENTS/euclient; then
               echo "Failed to change directory"
               exit 1
            fi
            echo "Pulling latest code from origin/main"
            if ! git pull origin main; then
               echo "Failed to pull latest codes"
               exit 1
            fi
            echo "Install Dependencies"
            if ! yarn install; then
               echo "Failed to Install dependencies"
               exit 1
            fi
            echo "successfully Pulled"
            # yarn run build
            # pm2 start yarn --name eu-africa-client --start
            # pm2 startup
